# -*- coding: utf-8 -*-

 # Wunderground Full Weather dictionary
wconditions = { 'Light Drizzle': "☂",
                'Heavy Drizzle': "☂",
                'Drizzle': "☂", 
                'Light Thunderstorm': "⚡", 
                'Heavy Thunderstorm': "⚡",
                'Rain': "☂",
                'Light Rain': "☂",
                'Heavy Rain': "☂",
                'Chance of Rain': "☂",
                'Light Rain Showers': "☂",
                'Heavy Rain Showers': "☂",
                'Light Thunderstorms and Rain': "⚡ ☂",
                'Heavy Thunderstorms and Rain': "⚡ ☂",
                'Light Rain Mist': "☂",
                'Heavy Rain Mist': "☂",
                'Light Spray': "☂",
                'Heavy Spray': "☂",
                'Snow': "☃",
                'Light Snow': "☃",
                'Heavy Snow': "☃",
                'Light Snow Showers': "☃",
                'Light Thunderstorms and Snow': "☃ ⚡",
                'Heavy Thunderstorms and Snow': "☃ ⚡",
                'Heavy Snow Showers': "☃",
                'Blowing Snow': "☃",
                'Light Blowing Snow': "☃",
                'Heavy Blowing Snow': "☃",
                'Light Low Drifting Snow': "☃",
                'Heavy Low Drifting Snow': "☃",
                'Light Snow Blowing Snow Mist': "☃",
                'Heavy Snow Blowing Snow Mist': "☃",
                'Light Snow Grains': "☃",
                'Heavy Snow Grains': "☃",
                'Light Ice Crystals': "❄",
                'Heavy Ice Crystals': "❄",
                'Ice Pellets': "❄",
                'Light Ice Pellets': "❄",
                'Heavy Ice Pellets': "❄",
                'Light Ice Pellet Showers': "❄",
                'Heavy Ice Pellet Showers': "❄",
                'Light Freezing Drizzle': "☂ ❄",
                'Heavy Freezing Drizzle': "☂ ❄",
                'Light Freezing Rain': "☂ ❄",
                'Heavy Freezing Rain': "☂ ❄",
                'Light Thunderstorms and Ice Pellets': "❄⚡",
                'Heavy Thunderstorms and Ice Pellets': "❄⚡",
                'Light Hail': "☍",
                'Heavy Hail': "☍",
                'Small Hail': "☍",
                'Light Hail Showers': "☍",
                'Heavy Hail Showers': "☍",
                'Light Small Hail Showers': "☍",
                'Heavy Small Hail Showers': "☍",
                'Light Thunderstorms with Hail': "☍⚡",
                'Light Thunderstorms with Hail': "☍⚡",
                'Light Thunderstorms with Small Hail': "☍⚡",
                'Heavy Thunderstorms with Small Hail': "☍⚡",
                'Fog': "₣",
                'Light Mist': "#",
                'Heavy Mist': "#",
                'Light Fog': "₣",
                'Heavy Fog': "₣",
                'Light Freezing Fog': "₣❄",
                'Heavy Freezing Fog': "₣❄",
                'Patches of Fog': "₣",
                'Shallow Fog': "₣",
                'Partial Fog': "₣",
                'Light Fog Patches': "₣",
                'Heavy Fog Patches': "₣",
                'Smoke': "S",
                'Widespread Dust': "D",
                'Light Blowing Widespread Dust': "D",
                'Heavy Blowing Widespread Dust': "D",
                'Light Low Drifting Widespread Dust': "D",
                'Heavy Low Drifting Widespread Dust': "D",
                'Light Dust Whirls': "D",
                'Heavy Dust Whirls': "D",
                'Light Sandstorm': "SS",
                'Heavy Sandstorm': "SS",
                'Light Sand': "SS",
                'Heavy Sand': "SS",
                'Light Blowing Sand': "SS",
                'Heavy Blowing Sand': "SS",
                'Light Low Drifting Sand': "SS",
                'Heavy Low Drifting Sand': "SS",
                'Clear': "☉",
                'Sunny': "☼",
                'Mostly Sunny': "☼☁",
                'Partly Cloudy': "☁ ☼",
                'Mostly Cloudy': "☁",
                'Scattered Clouds': "☁",
                'Chance of Storm': "☁ ☂",
                'Showers': "☂",
                'Chance of Snow': "☃",
                'Storm': "☈",
                'Thunderstorm': "⚡",
                'Sleet': "S",
                'Icy': "I",
                'Haze': "H",
                'Light Haze': "H",
                'Heavy Haze': "H",
                'Flurries': "*",
                'Overcast': "☁",
                'Funnel Cloud': "Run!!!!",
                'Squals': "SQ"}
